### PR TITLE
Fixed some type hints of ReplayBuffer

### PR DESCRIPTION
**Pull request by JanS97**
## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context / Related issue

The type hints for `obs_shape` and `action_shape` (`Tuple[int]`) only allowed tuples with one element. Hence, the type checker complained when using `ReplayBuffer` with multi-dimensional observations / actions, even though it works fine (in fact I have been using `ReplayBuffer` with image observations for quite some time now). Instead of changing the type hints to `Tuple[int, ...]`, I changed them to `Iterable[int]` since it works just as fine and make the class easier to use (it also allows passing the shape e.g. as list instead of tuple).

Furthermore, I changed the type of the return value of `sample()` since it was a little unspecific. The function always returns a `TransitionBatch`. Because the type hint was `Sized`, the type checker complained if e.g. `replay_buffer.sample(1).obs` is executed.

## How Has This Been Tested (if it applies)

```
import numpy as np
from omegaconf import DictConfig

from mbrl.util.common import create_replay_buffer

cfg = DictConfig({"overrides": {"num_steps": 42}})
obs_shape = [1, 2, 3]
action_shape = [1, 2]
replay = create_replay_buffer(cfg, obs_shape, action_shape)

obs = np.random.random(obs_shape).astype(np.float32)
action = np.random.random(action_shape).astype(np.float32)
next_obs = np.random.random(obs_shape).astype(np.float32)
replay.add(obs, action, next_obs, 0.0, False)
batch_sampled = replay.sample(1)
assert np.all(batch_sampled.obs[0] == obs)
assert np.all(batch_sampled.act[0] == action)
assert np.all(batch_sampled.next_obs[0] == next_obs)
```

Running mypy on the program above, yields no type errors.

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the [**CONTRIBUTING**](../../CONTRIBUTING.md) document and completed the CLA (see **CONTRIBUTING**).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Comment by luisenp** [comment]
Thanks! I have [similar](https://github.com/facebookresearch/mbrl-lib/pull/86/files#diff-ba2d6b5b3f6bb7e8bf34c895e2999b66545c4482c0fc5f884357a20a7c1315a8L166) changes in an ongoing PlaNet brach, but happy to merge this in the mean time. But maybe `Sequence` would be slightly better type hint than `Iterable` for the shapes?

**Comment by JanS97** [comment]
Ah ok, I did not have a closer look at the PlaNet branch.
Since Sequence inherits from Iterable and the parameters values are used only with the unpacking operator `*`, which should work for general Iterables, using Iterable is slightly more general here. Of course I agree that probably nobody would use a something that is not a Sequence here, so I would not object to using Sequence. Why do prefer Sequence?

**Comment by luisenp** [comment]
One reason for using `Sequence` would be that some iterables are not necessarily ordered (but sequences are), so you could pass something like a set, for which the order of creation could be different than the order of unpacking, which would result in unwanted behavior. Using `Iterable` in some sense endorses this strange user behavior.

**Comment by JanS97** [comment]
Good point. I'll change the type hints to `Sequence`.

**Pull request merged**
