### PR TITLE
PID code and Update Readme

### PR DESCRIPTION
**Pull request by natolambert**
The minimum changes to get a notebook running for #158.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the [**CONTRIBUTING**](../../CONTRIBUTING.md) document and completed the CLA (see **CONTRIBUTING**).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Review by luisenp — CHANGES_REQUESTED** [review]
LGTM! Just need to fix some CI errors. Thanks for adding this!

**Comment by natolambert** [comment]
Ah, oops. Will come back to this within a couple days!

**Comment by natolambert** [comment]
@luisenp should be good? Its annoying to run the pre-commits hardcoded to 3.7 with conda no longer supporting it. Looking forward to that update being merged into main :)

**Comment by luisenp** [comment]
Merged! Thanks for the contribution @natolambert!

**Comment by natolambert** [comment]
Awesome, excited to finally be listed as a contributor. I hope to continue in the future!

**Pull request merged**
